---
- name: Exercise2 - Juniper and Ansible
  hosts: pynet-sf-srx
  tasks:
    - name: Verifying NETCONF
      wait_for: host={{ ansible_ssh_host }} port=830

    - name: Change host name to 'foo'
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=exercise2.conf
        overwrite=false
        user={{ juniper_user }}
        passwd={{ juniper_passwd }}
