---

- name: Arista Trunking
  hosts: arista
  
  tasks:
    - name: Configure Ethernet2 to trunk
      eos_switchport: name=Ethernet2 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=172,272,372
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
