---

- name: Create Arista VLANs
  hosts: arista
  
  tasks:
    - name: create SERVER VLAN
      eos_vlan: name=SERVER vlanid=172
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
            
    - name: create USER VLAN
      eos_vlan: name=USER vlanid=272
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
            
    - name: create PRINTER VLAN
      eos_vlan: name=PRINTER vlanid=372
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
